Mobile-desktop popup
Elhambasir/MyPortfolio pull request #12
Opened 2023-03-09 07:54 UTC by Elhambasir

Popup window is done for mobile and desktop versions.

2023-03-09 21:41 UTC, christianbiring1 requested changes
Hi @Elhambasir @Nelofarzabi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/224166356-e21ab762-c0ac-4a51-9507-d603cbc55490.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title`
- [ ] The projects are rendered dynamically :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] `Telling in detail in the description box a descriptive summary of what changes you have implemented in the PR.`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 21:41 UTC, christianbiring1 commented on style.css
> +}
- [ ] Great job on rendering the projects list dynamically :+1: However, Kindly consider making sure when the pop modal is activated the user can't scroll anymore to overpass it as is the case on your design.
Hint: `to fix this issue, you may consider adding a container  for the pop-up in the HTML doc, give it the absolute position according to the body element, and center it as you did for the pop up and I hope from there you will be good to go.`

### Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/224162515-0cf51e31-cde1-4705-b069-8a3c01002b99.png)
![image](https://user-images.githubusercontent.com/97100091/224162586-c0dea2ae-59ad-467c-b9d1-5b8c317da0cc.png)

2023-03-09 21:41 UTC, christianbiring1 commented on style.css
> +  text-align: right;
- [ ] Kindly make sure you stick to the design as much as possible, the spacing(margin, padding) should suppose to be similar to the Figma design.

### Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/224164540-f12032b3-f3d2-4d59-b22f-00f60888c6bd.png)
### 2
![image](https://user-images.githubusercontent.com/97100091/224164745-27748ed1-eca2-45b1-97f3-2dcb7eb129b8.png)


### Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/224164436-503788d6-31fc-488e-8e87-9a1038b6c2f6.png)

### 2

![image](https://user-images.githubusercontent.com/97100091/224165214-cf7645aa-60a0-4d2c-9797-83dfb28a23ee.png)

2023-03-10 10:39 UTC, frank1738 approved these changes
Hi @Elhambasir , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good commit messeges

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 11:07 UTC, merged